version: '3'

services:
  api:
    image: webapp
    restart: always
    container_name: mywebapp
    build:
        context: ./src
    volumes:
      - ./src/myApp:/usr/local/tomcat/webapps/myApp
      # Exclude this from volume.
      - /usr/local/tomcat/webapps/myApp/WEB-INF/classes
    ports:
      - "80:8080"